### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'eval'

### ISSUE THREAD

**Issue by SikangSHU** [alexjfoote/reetoolbox#1]
Hi!
An error occurred when I run this program, do you know how to solve it? Thank you very much!
![image](https://user-images.githubusercontent.com/95743639/153696251-a4ab6c9b-98f7-4df5-b746-b6572c821808.png)

**Comment by alexjfoote** [comment]
Hi there, 
It looks like the model that you have given to the evaluator is an OrderedDict rather than a PyTorch model. If you send the code that loads your model I'll take a look at what's going wrong.

**Comment by SikangSHU** [comment]
> Hi there, It looks like the model that you have given to the evaluator is an OrderedDict rather than a PyTorch model. If you send the code that loads your model I'll take a look at what's going wrong.

Hello, I have used ```cpu``` and```torch.load(model_path)``` to load the model before. After trying to use ```cuda```, the program runs well.

**Comment by alexjfoote** [comment]
Great, I’m glad you’ve got it working. I’ll try and reproduce the problem using `cpu` and see if something needs to be fixed.
